use_frameworks!

target 'Progress_Example' do
  pod 'Progress', :path => '../'

  target 'Progress_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.1'
  pod 'Nimble', '~> 7.3.1'
  end
end
