use_frameworks!

target 'Progress_Example' do
  pod 'Progress', :path => '../'

  target 'Progress_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
